document:
  name: Linee Guida Attribute Authority SPID
  description: |
    Linee Guida contenenti le regole tecniche dei gestori di attributi qualificati ex art.1, comma 1, lettera m) del DPCM 24 ottobre 2014 (GU n.285 del 9­12­2014)
  tags:
    - "spid"
