document:
  name: Linee guida contenenti le regole tecniche dei gestori di attributi qualificati

  description:
      Linee guida contenenti le regole tecniche dei gestori di attributi qualificati
  tags:
    - spid
    - linee guida